/**
 * Restore snippets run by the shell wrappers after the user's startup files (H36, design §3.5).
 * Static text: values come from the AIBORG_* vars applyClientProfileEnv set, so terminals
 * without a profile (no AIBORG_PROFILE_ID) are untouched. Keys are validated env names, which
 * is what makes the `eval` / `Env:` indirection safe.
 */

function posixRestore(split: (name: string) => string): string {
  return `# AI-Borg: re-apply the client profile env after user startup files.
if [ -n "\${AIBORG_PROFILE_ID:-}" ]; then
  for __aiborg_key in ${split('AIBORG_PROFILE_UNSET')}; do unset "$__aiborg_key"; done
  for __aiborg_key in ${split('AIBORG_PROFILE_KEYS')}; do
    eval "export $__aiborg_key=\\"\\\${AIBORG_KEEP_$__aiborg_key}\\""
  done
  __aiborg_bin="\${AIBORG_PROFILE_BIN:-}"
  # Why: Git Bash converts PATH to /c/... form at startup; the kept value is a Windows path.
  if command -v cygpath >/dev/null 2>&1; then __aiborg_bin=$(cygpath -u "$__aiborg_bin"); fi
  case ":$PATH:" in *":$__aiborg_bin:"*) ;; *) export PATH="$__aiborg_bin:$PATH" ;; esac
  __aiborg_hex="\${AIBORG_PROFILE_COLOR:-#888888}"
  __aiborg_rgb="$((16#\${__aiborg_hex:1:2}));$((16#\${__aiborg_hex:3:2}));$((16#\${__aiborg_hex:5:2}))"
  __aiborg_label="\${AIBORG_PROFILE_NAME//[^A-Za-z0-9 ._-]/}"
`
}

/** bash: local provider and daemon rcfiles. */
export function getClientProfileBashRestoreSnippet(): string {
  return `${posixRestore((name) => `\${${name}:-}`)}  __aiborg_prompt_prefix="\\[\\033[38;2;\${__aiborg_rgb}m\\][\${__aiborg_label}]\\[\\033[0m\\] "
  __aiborg_apply_prompt() {
    case "$PS1" in *"$__aiborg_prompt_prefix"*) ;; *) PS1="$__aiborg_prompt_prefix$PS1" ;; esac
  }
  __aiborg_apply_prompt
  # Why every prompt: prompt frameworks rebuild PS1 from PROMPT_COMMAND.
  case ";\${PROMPT_COMMAND:-};" in
    *__aiborg_apply_prompt*) ;;
    *) PROMPT_COMMAND="\${PROMPT_COMMAND:+\${PROMPT_COMMAND%;};}__aiborg_apply_prompt" ;;
  esac
  unset __aiborg_key __aiborg_bin __aiborg_hex __aiborg_rgb __aiborg_label
fi
`
}

/** zsh: `${=VAR}` because zsh does not word-split unquoted parameters. */
export function getClientProfileZshRestoreSnippet(): string {
  return `${posixRestore((name) => `\${=\${${name}:-}}`)}  typeset -g __aiborg_prompt_prefix="%{"$'\\e'"[38;2;\${__aiborg_rgb}m%}[\${__aiborg_label}]%{"$'\\e'"[0m%} "
  __aiborg_apply_prompt() {
    [[ "$PROMPT" == *"$__aiborg_prompt_prefix"* ]] || PROMPT="$__aiborg_prompt_prefix$PROMPT"
  }
  __aiborg_apply_prompt
  # Why a precmd hook: powerlevel10k and most oh-my-zsh themes rebuild PROMPT before each prompt.
  autoload -Uz add-zsh-hook && add-zsh-hook precmd __aiborg_apply_prompt
  unset __aiborg_key __aiborg_bin __aiborg_hex __aiborg_rgb __aiborg_label
fi
`
}

/** P/bin file the PowerShell bootstrap loads for the prompt label (FullLanguage only). */
export const CLIENT_PROFILE_POWERSHELL_PROMPT_FILE = 'aiborg-prompt.ps1'

/** Contents of P/bin/aiborg-prompt.ps1: profile-independent, it reads the AIBORG_* env. */
export function getClientProfilePowerShellPromptScript(): string {
  return `# generated by AI-Borg; do not edit
$__aiborgHex = if ($env:AIBORG_PROFILE_COLOR -match '^#[0-9a-fA-F]{6}$') { $env:AIBORG_PROFILE_COLOR } else { '#888888' }
$Global:__AiborgPromptPrefix = "$([char]27)[38;2;$([Convert]::ToInt32($__aiborgHex.Substring(1,2),16));$([Convert]::ToInt32($__aiborgHex.Substring(3,2),16));$([Convert]::ToInt32($__aiborgHex.Substring(5,2),16))m[$($env:AIBORG_PROFILE_NAME -replace '[^A-Za-z0-9 ._-]','')]$([char]27)[0m "
# Why wrap Orca's saved prompt when present: the label then sits after the OSC 133;A mark.
if ((Test-Path variable:global:__OrcaOsc133State) -and $null -ne $Global:__OrcaOsc133State.OriginalPrompt) {
    $Global:__AiborgInnerPrompt = $Global:__OrcaOsc133State.OriginalPrompt
    $Global:__OrcaOsc133State.OriginalPrompt = { $Global:__AiborgPromptPrefix + (& $Global:__AiborgInnerPrompt) }
} else {
    $Global:__AiborgInnerPrompt = $function:prompt
    function Global:prompt { $Global:__AiborgPromptPrefix + (& $Global:__AiborgInnerPrompt) }
}
Remove-Variable -Name __aiborgHex -ErrorAction SilentlyContinue
`
}

/**
 * PowerShell: appended to getPowerShellOsc133Bootstrap(), which runs after $PROFILE. Kept short:
 * it travels in every terminal's -EncodedCommand, profile or not, against the 32,767-char
 * command-line limit. The env restore stays inline (dot-sourcing a file is execution-policy
 * gated); the prompt label is read from P/bin as text, which the policy does not gate.
 */
export function getClientProfilePowerShellRestoreSnippet(): string {
  return `# AI-Borg: re-apply the client profile env after the user profile scripts.
if ($env:AIBORG_PROFILE_ID) {
foreach ($__aiborgK in "$env:AIBORG_PROFILE_UNSET".Split(' ')) { if ($__aiborgK) { Remove-Item -LiteralPath "Env:$__aiborgK" -EA 0 } }
foreach ($__aiborgK in "$env:AIBORG_PROFILE_KEYS".Split(' ')) { if ($__aiborgK) { Set-Item -LiteralPath "Env:$__aiborgK" -Value ([Environment]::GetEnvironmentVariable("AIBORG_KEEP_$__aiborgK")) } }
if ($env:AIBORG_PROFILE_BIN) {
$__aiborgK = [IO.Path]::PathSeparator
if (($env:PATH -split $__aiborgK) -notcontains $env:AIBORG_PROFILE_BIN) { $env:PATH = "$env:AIBORG_PROFILE_BIN$__aiborgK$env:PATH" }
$__aiborgK = Join-Path $env:AIBORG_PROFILE_BIN '${CLIENT_PROFILE_POWERSHELL_PROMPT_FILE}'
if ($ExecutionContext.SessionState.LanguageMode -eq 'FullLanguage' -and (Test-Path -LiteralPath $__aiborgK)) { . ([scriptblock]::Create([IO.File]::ReadAllText($__aiborgK))) }
}
Remove-Variable -Name __aiborgK -EA 0
}
`
}
