import { join } from 'node:path'
import type {
  ClientProfile,
  ClientProfileMachineSettings
} from '../../../shared/aiborg/client-profile-types'
import { clientProfileSshPublicKeyPath } from '../../../shared/aiborg/client-profile-schema'
import { toGitPath, type ClientProfileHomeLayout } from './client-profile-paths'

/** Scheme `pushInsteadOf` rewrites disallowed pushes to; git then runs `git-remote-aiborg-blocked`. */
export const AIBORG_BLOCKED_SCHEME = 'aiborg-blocked'

export type PushInsteadOfRule = { base: string; prefix: string }

export function resolveWindowsSshPath(
  machine: Pick<ClientProfileMachineSettings, 'windowsSsh'>,
  env: NodeJS.ProcessEnv
): string {
  if (machine.windowsSsh) {
    return toGitPath(machine.windowsSsh)
  }
  // Why System32 OpenSSH: the Bitwarden agent listens on its named pipe; Git's bundled ssh does not.
  return toGitPath(join(env.SystemRoot ?? 'C:\\Windows', 'System32', 'OpenSSH', 'ssh.exe'))
}

export function clientProfileSshKeyPath(
  profile: Pick<ClientProfile, 'git'>,
  layout: ClientProfileHomeLayout
): string {
  return join(layout.home, ...clientProfileSshPublicKeyPath(profile).split(/[\\/]/))
}

/** `-F` keeps `~/.ssh/config` IdentityFile entries (personal keys) out of profile pushes. */
export function buildClientProfileSshCommand(input: {
  profile: Pick<ClientProfile, 'git'>
  layout: ClientProfileHomeLayout
  platform: NodeJS.Platform
  machine: Pick<ClientProfileMachineSettings, 'windowsSsh'>
  env: NodeJS.ProcessEnv
}): string {
  const ssh =
    input.platform === 'win32' ? `"${resolveWindowsSshPath(input.machine, input.env)}"` : 'ssh'
  const key = toGitPath(clientProfileSshKeyPath(input.profile, input.layout))
  const config = toGitPath(input.layout.sshConfig)
  return `${ssh} -F "${config}" -o IdentitiesOnly=yes -o BatchMode=yes -i "${key}"`
}

export function buildClientProfileSshConfig(
  profile: Pick<ClientProfile, 'id' | 'git'>,
  layout: ClientProfileHomeLayout
): string {
  return [
    `# generated by AI-Borg for profile ${profile.id}; do not edit`,
    'Host *',
    '  IdentitiesOnly yes',
    `  IdentityFile "${toGitPath(clientProfileSshKeyPath(profile, layout))}"`,
    ''
  ].join('\n')
}

/**
 * URL spellings git treats as different prefixes for one host: userinfo GitHub accepts over
 * HTTPS, the explicit SSH port, and github.com's SSH-over-443 host. Other spellings (arbitrary
 * userinfo, IP addresses) are left to the pre-push hook and the app-level guard.
 */
export function clientProfilePushUrlPrefixes(host: string): string[] {
  const prefixes = [
    `https://${host}/`,
    `https://git@${host}/`,
    `https://x-access-token@${host}/`,
    `https://oauth2@${host}/`,
    `git@${host}:`,
    `ssh://git@${host}/`,
    `ssh://git@${host}:22/`
  ]
  if (host === 'github.com') {
    prefixes.push(
      'git@ssh.github.com:',
      'ssh://git@ssh.github.com/',
      'ssh://git@ssh.github.com:443/'
    )
  }
  return prefixes
}

/** Longest-prefix wins, so only allowed orgs keep a pushable URL (§5.2 layer 3). */
export function buildPushInsteadOfRules(
  profile: Pick<ClientProfile, 'github'>
): PushInsteadOfRule[] {
  const prefixes = clientProfilePushUrlPrefixes(profile.github.host)
  const blocked = prefixes.map((prefix) => ({ base: `${AIBORG_BLOCKED_SCHEME}://`, prefix }))
  const identity = profile.github.allowedOrgs.flatMap((org) =>
    prefixes.map((prefix) => ({ base: `${prefix}${org}/`, prefix: `${prefix}${org}/` }))
  )
  return [...blocked, ...identity]
}

/** Command-scope entries: they beat repo-local hooksPath (husky) and identity. */
export function buildClientProfileCommandScopeGitConfig(
  profile: Pick<ClientProfile, 'git' | 'github'>,
  layout: ClientProfileHomeLayout
): [string, string][] {
  return [
    ['core.hooksPath', toGitPath(layout.hooks)],
    ['user.name', profile.git.userName],
    ['user.email', profile.git.userEmail],
    ...buildPushInsteadOfRules(profile).map((rule): [string, string] => [
      `url.${rule.base}.pushInsteadOf`,
      rule.prefix
    ])
  ]
}

/** Quotes a gitconfig value; `"` and `\` are syntax there. */
export function gitConfigQuote(value: string): string {
  return `"${value.replaceAll('\\', '\\\\').replaceAll('"', '\\"').replaceAll('\n', '\\n')}"`
}

function subsection(name: string): string {
  return name.replaceAll('\\', '\\\\').replaceAll('"', '\\"')
}

/** `[safe] directory` values from a gitconfig file; git reads safe.directory only from global scope. */
export function parseSafeDirectories(gitconfigText: string): string[] {
  const directories: string[] = []
  let inSafe = false
  for (const rawLine of gitconfigText.split(/\r?\n/)) {
    const line = rawLine.trim()
    const header = line.match(/^\[([^\]]+)\]/)
    if (header) {
      inSafe = header[1].trim().toLowerCase() === 'safe'
      continue
    }
    const entry = inSafe ? line.match(/^directory\s*=\s*(.*)$/i) : null
    if (entry) {
      const value = entry[1].replace(/\s+[;#].*$/, '').trim()
      directories.push(value.replace(/^"(.*)"$/, '$1').replaceAll('\\\\', '\\'))
    }
  }
  return directories.filter(Boolean)
}

export function buildClientProfileGitconfig(input: {
  profile: ClientProfile
  layout: ClientProfileHomeLayout
  platform: NodeJS.Platform
  sshCommand: string
  safeDirectories: readonly string[]
}): string {
  const { profile, layout } = input
  const lines = [`# generated by AI-Borg for profile ${profile.id}; do not edit`]
  // Why first: later sections then reset what the user's file sets (credential helpers).
  if (profile.git.includeGlobalGitconfig) {
    lines.push('[include]', '\tpath = ~/.gitconfig')
  }
  lines.push(
    '[user]',
    `\tname = ${gitConfigQuote(profile.git.userName)}`,
    `\temail = ${gitConfigQuote(profile.git.userEmail)}`,
    '[core]',
    `\tsshCommand = ${gitConfigQuote(input.sshCommand)}`,
    `\thooksPath = ${gitConfigQuote(toGitPath(layout.hooks))}`
  )
  if (input.platform === 'win32') {
    lines.push('\tlongpaths = true')
  }
  // Why the empty helper: GIT_CONFIG_GLOBAL does not hide system config (Git for Windows' GCM).
  lines.push(
    '[credential]',
    '\thelper =',
    `[credential "https://${subsection(profile.github.host)}"]`,
    '\thelper =',
    '\thelper = !gh auth git-credential',
    '[filter "lfs"]',
    '\tclean = git-lfs clean -- %f',
    '\tsmudge = git-lfs smudge -- %f',
    '\tprocess = git-lfs filter-process',
    '\trequired = true'
  )
  if (input.safeDirectories.length > 0) {
    lines.push(
      '[safe]',
      ...input.safeDirectories.map((dir) => `\tdirectory = ${gitConfigQuote(dir)}`)
    )
  }
  const rulesByBase = new Map<string, string[]>()
  for (const rule of buildPushInsteadOfRules(profile)) {
    rulesByBase.set(rule.base, [...(rulesByBase.get(rule.base) ?? []), rule.prefix])
  }
  for (const [base, prefixes] of rulesByBase) {
    lines.push(
      `[url "${subsection(base)}"]`,
      ...prefixes.map((p) => `\tpushInsteadOf = ${gitConfigQuote(p)}`)
    )
  }
  return `${lines.join('\n')}\n`
}
