import type { ClientProfile } from '../../../shared/aiborg/client-profile-types'
import { toGitPath, type ClientProfileHomeLayout } from './client-profile-paths'
import { AIBORG_BLOCKED_SCHEME } from './client-profile-git-templates'

export const CLIENT_PROFILE_CHAIN_STUB = '.chain'
export const BLOCKED_REMOTE_HELPER_NAME = `git-remote-${AIBORG_BLOCKED_SCHEME}`

// Why not reference-transaction / post-index-change: they fire on every ref or index write
// (Orca's own status polling), and one sh spawn each would slow every git call on Windows.
export const CLIENT_PROFILE_CHAINED_HOOK_NAMES = [
  'applypatch-msg',
  'pre-applypatch',
  'post-applypatch',
  'pre-commit',
  'pre-merge-commit',
  'prepare-commit-msg',
  'commit-msg',
  'post-commit',
  'pre-rebase',
  'post-checkout',
  'post-merge',
  'post-rewrite',
  'pre-auto-gc',
  'sendemail-validate',
  // Server side: a push to a local bare repo inherits the command-scope hooksPath.
  'pre-receive',
  'update',
  'post-receive',
  'post-update'
] as const

export function shSingleQuote(value: string): string {
  return `'${value.replaceAll("'", `'\\''`)}'`
}

function header(profileId: string): string {
  return `#!/bin/sh\n# generated by AI-Borg for profile ${profileId}; do not edit\n`
}

function regexEscape(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\#]/g, '\\$&')
}

function auditPrintf(profileId: string, auditPath: string, via: 'hook' | 'rewrite'): string {
  return [
    `safe_remote=$(printf '%s' "$remote" | tr -d '"\\\\\\r\\n')`,
    `safe_owner=$(printf '%s' "$owner" | tr -d '"\\\\\\r\\n')`,
    `printf '{"ts":"%s","event":"push.blocked","profileId":"%s","remote":"%s","owner":"%s","via":"${via}"}\\n' \\`,
    `  "$(date -u +%Y-%m-%dT%H:%M:%SZ)" ${shSingleQuote(profileId)} "$safe_remote" "$safe_owner" >> ${shSingleQuote(toGitPath(auditPath))} 2>/dev/null`
  ].join('\n')
}

function blockMessage(profile: Pick<ClientProfile, 'name' | 'github'>): string {
  const allowed = profile.github.allowedOrgs.join(' ')
  return `echo "AI-Borg: push to '\${owner:-$url}' blocked: profile "${shSingleQuote(profile.name)}" only allows: "${shSingleQuote(allowed)} >&2`
}

/** Orgs are baked in so the guard does not depend on AIBORG_ALLOWED_ORGS surviving in the env. */
export function buildPrePushHook(
  profile: Pick<ClientProfile, 'id' | 'name' | 'github'>,
  layout: ClientProfileHomeLayout
): string {
  // Why the ssh. alternative: github.com also serves SSH on ssh.github.com:443. sed -E has no
  // non-capturing group, so the owner's group index shifts with it.
  const sshAlias = profile.github.host === 'github.com'
  const host = sshAlias ? '(ssh\\.)?github\\.com' : regexEscape(profile.github.host)
  const urlOwner = sshAlias ? 4 : 3
  const scpOwner = sshAlias ? 3 : 2
  const allowed = profile.github.allowedOrgs.join(' ')
  return `${header(profile.id)}remote="$1"
url="$2"
allowed=${shSingleQuote(allowed)}
owner=$(printf '%s\\n' "$url" | sed -E -n \\
  -e 's#^[A-Za-z][A-Za-z0-9+.-]*://([^@/]*@)?${host}(:[0-9]+)?/+([^/]+)/.*$#\\${urlOwner}#p' \\
  -e 's#^([^@/:]*@)?${host}:/*([^/]+)/.*$#\\${scpOwner}#p' | head -n 1 | tr 'A-Z' 'a-z')
if [ -n "$owner" ]; then
  case " $allowed " in
    *" $owner "*) exec sh ${shSingleQuote(toGitPath(`${layout.hooks}/${CLIENT_PROFILE_CHAIN_STUB}`))} pre-push "$@" ;;
  esac
fi
${auditPrintf(profile.id, layout.audit, 'hook')}
${blockMessage(profile)}
exit 1
`
}

/**
 * Runs the repo's own `$name` hook: local core.hooksPath, else <git-common-dir>/hooks.
 * Why builtins only on the common path: every hook event runs this, Orca's own git included, and
 * each extra process (sh, git) costs tens of ms on Git for Windows. git is asked only when the
 * repo config may set core.hooksPath or pulls in other files.
 */
function chainBody(layout: ClientProfileHomeLayout): string {
  return `gd=\${GIT_DIR:-.git}
if [ -f "$gd" ]; then
  IFS= read -r line < "$gd" || [ -n "$line" ]
  gd=\${line#gitdir: }
fi
common=$gd
if [ -f "$gd/commondir" ]; then
  IFS= read -r rel < "$gd/commondir" || [ -n "$rel" ]
  case "$rel" in
    /*|[A-Za-z]:*) common=$rel ;;
    *) common="$gd/$rel" ;;
  esac
fi
dir=
if [ -f "$common/config" ] && [ ! -f "$gd/config.worktree" ]; then
  dir="$common/hooks"
  while IFS= read -r l || [ -n "$l" ]; do
    case "$l" in
      *[hH][oO][oO][kK][sS][pP][aA][tT][hH]*|*'['[iI][nN][cC][lL][uU][dD][eE]*) dir= ; break ;;
    esac
  done < "$common/config"
fi
if [ -z "$dir" ]; then
  self=$(cd ${shSingleQuote(toGitPath(layout.hooks))} 2>/dev/null && pwd -P)
  dir=$(git config --local --type=path core.hooksPath 2>/dev/null)
  if [ -z "$dir" ]; then
    common=$(git rev-parse --git-common-dir 2>/dev/null) || exit 0
    dir="$common/hooks"
  fi
  real=$(cd "$dir" 2>/dev/null && pwd -P) || exit 0
  if [ "$real" = "$self" ]; then
    exit 0
  fi
  dir=$real
fi
hook="$dir/$name"
if [ -f "$hook" ] && [ -x "$hook" ]; then
  exec "$hook" "$@"
fi
exit 0
`
}

/** `.chain <name> [args]`: the pre-push hook hands allowed pushes to the repo's own hook here. */
export function buildHookChainStub(profileId: string, layout: ClientProfileHomeLayout): string {
  return `${header(profileId)}name="$1"
shift
${chainBody(layout)}`
}

/** One sh process per hook event: the chain logic is inlined, not exec'd. */
export function buildPassThroughHook(
  profileId: string,
  hookName: string,
  layout: ClientProfileHomeLayout
): string {
  return `${header(profileId)}name=${shSingleQuote(hookName)}
${chainBody(layout)}`
}

/** Remote helper for rewritten pushes; hooks never run on this path, so it audits itself. */
export function buildBlockedRemoteHelper(
  profile: Pick<ClientProfile, 'id' | 'name' | 'github'>,
  layout: ClientProfileHomeLayout
): string {
  return `${header(profile.id)}remote="$1"
url="$2"
owner=$(printf '%s\\n' "$url" | sed -E -n 's#^${AIBORG_BLOCKED_SCHEME}://+([^/]+).*$#\\1#p' | head -n 1 | tr 'A-Z' 'a-z')
${auditPrintf(profile.id, layout.audit, 'rewrite')}
${blockMessage(profile)}
exit 1
`
}
